Generate CSR using wasm module
cisco-open/wasm-kernel-module pull request #29
Opened 2023-08-03 18:57 UTC by baluchicken

## Description

This PR generates a rsa keypair inside a kernel using bearSSL. The stored key will then be used to generate a certificate signing request using a wasm module. (bearSSL at the moment does not support this). This CSR will then be used in an agent code(e.g.: istio controlplane) to generate a proper certificate.

## Type of Change

- [ ] Bug Fix
- [X] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-08-07 14:04 UTC, bonifaido commented on rsa_tools.c
> +    uint32_t result = rsa_keygen(&hmac_drbg_ctx.vtable, rsa_priv, raw_priv_key, rsa_pub, raw_pub_key, 2048, 3);
can be an inline return

2023-08-07 14:06 UTC, bonifaido requested changes

2023-08-07 14:06 UTC, bonifaido commented on rsa_tools.c
> +    size_t len = br_encode_rsa_pkcs8_der(der, rsa_priv, rsa_pub, priv_exponent, priv_exponent_size);
inline return

2023-08-07 14:06 UTC, bonifaido commented on socket.c
> +	c->rsa_priv = kzalloc(sizeof(br_rsa_private_key), GFP_KERNEL);
Are these new allocations freed anywhere?

2023-08-07 14:41 UTC, baluchicken commented on socket.c
> +	c->rsa_priv = kzalloc(sizeof(br_rsa_private_key), GFP_KERNEL);
Yes:) now they are freed `free_wasm_socket_context` function.

2023-08-08 08:03 UTC, bonifaido commented on rsa_tools.c
> +        printk(KERN_ERR "system source of randomness failed");
This is a fatal error, so we should call `BUG()` here, see `assert.h`.

2023-08-08 08:14 UTC, bonifaido commented on socket.c
> +			kfree(sc->rsa_priv);
Common parts could be moved out from the boolean arms.

2023-08-08 08:39 UTC, bonifaido approved these changes

2023-08-08 08:49 UTC, bonifaido approved these changes

2023-08-08 08:50 UTC, merged